--
-- PostgreSQL database dump
--

-- Dumped from database version 16.9
-- Dumped by pg_dump version 16.9

-- Started on 2025-09-05 18:08:20

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- TOC entry 4874 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 215 (class 1259 OID 16398)
-- Name: event_categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.event_categories (
    id integer NOT NULL,
    name character varying NOT NULL,
    display_order integer NOT NULL
);


ALTER TABLE public.event_categories OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 16403)
-- Name: event_enrollments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.event_enrollments (
    descripcion character varying NOT NULL,
    "Registro_tiempo" time with time zone NOT NULL,
    asistencia integer NOT NULL,
    observaciones character varying NOT NULL,
    raiting integer NOT NULL,
    id integer NOT NULL,
    id_event integer NOT NULL,
    id_user integer NOT NULL
);


ALTER TABLE public.event_enrollments OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16408)
-- Name: event_locations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.event_locations (
    id integer NOT NULL,
    id_locations integer NOT NULL,
    nombre character varying NOT NULL,
    direccion character varying NOT NULL,
    capacidad_max character varying NOT NULL,
    latitud character varying NOT NULL,
    longitud character varying NOT NULL,
    id_creator_user integer NOT NULL
);


ALTER TABLE public.event_locations OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 16531)
-- Name: event_locations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.event_locations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.event_locations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 16413)
-- Name: event_registrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.event_registrations (
    id integer NOT NULL,
    id_event integer NOT NULL,
    id_user integer NOT NULL,
    fecha_registro timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.event_registrations OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16417)
-- Name: event_registrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.event_registrations_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.event_registrations_id_seq OWNER TO postgres;

--
-- TOC entry 4875 (class 0 OID 0)
-- Dependencies: 219
-- Name: event_registrations_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.event_registrations_id_seq OWNED BY public.event_registrations.id;


--
-- TOC entry 220 (class 1259 OID 16418)
-- Name: event_tags; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.event_tags (
    id integer NOT NULL,
    id_event integer NOT NULL,
    id_tag integer NOT NULL
);


ALTER TABLE public.event_tags OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16421)
-- Name: events; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.events (
    id integer NOT NULL,
    nombre character varying NOT NULL,
    descripcion character varying NOT NULL,
    id_evento_categoria integer NOT NULL,
    id_evento_locacion integer NOT NULL,
    fecha time with time zone NOT NULL,
    duracion_minutos integer NOT NULL,
    precio integer NOT NULL,
    inscripcion_activada integer NOT NULL,
    maxima_asistencia integer NOT NULL,
    id_creator_user integer NOT NULL
);


ALTER TABLE public.events OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 16426)
-- Name: locations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.locations (
    id integer NOT NULL,
    nombre character varying NOT NULL,
    latitud character varying NOT NULL,
    longitud character varying NOT NULL,
    id_provincia integer NOT NULL
);


ALTER TABLE public.locations OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16431)
-- Name: provinces; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.provinces (
    id integer NOT NULL,
    nombre character varying NOT NULL,
    nombre_completo character varying NOT NULL,
    latitud character varying NOT NULL,
    longitud character varying NOT NULL,
    display_order character varying NOT NULL
);


ALTER TABLE public.provinces OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 16436)
-- Name: tags; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tags (
    id integer NOT NULL,
    name character varying NOT NULL
);


ALTER TABLE public.tags OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16441)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id integer NOT NULL,
    primer_nombre character varying NOT NULL,
    ultimo_nombre character varying NOT NULL,
    username character varying NOT NULL,
    "contraseña" character varying NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 16446)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4672 (class 2604 OID 16447)
-- Name: event_registrations id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.event_registrations ALTER COLUMN id SET DEFAULT nextval('public.event_registrations_id_seq'::regclass);


--
-- TOC entry 4856 (class 0 OID 16398)
-- Dependencies: 215
-- Data for Name: event_categories; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.event_categories VALUES (1, 'Música', 1);


--
-- TOC entry 4857 (class 0 OID 16403)
-- Dependencies: 216
-- Data for Name: event_enrollments; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.event_enrollments VALUES ('Registrado vía web', '10:00:00-03', 20, 'ninguna', 0, 1, 1, 1);


--
-- TOC entry 4858 (class 0 OID 16408)
-- Dependencies: 217
-- Data for Name: event_locations; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.event_locations VALUES (1, 1, 'Auditorio Principal', 'Av. Sarmiento 2704, CABA', '500', '-5', '-58', 1);
INSERT INTO public.event_locations VALUES (9, 1, 'Nombre de la ubicación', 'Dirección completa', '200', '-34.5831', '-58.4108', 4);
INSERT INTO public.event_locations VALUES (11, 1, 'Palermo', '31232', '500', '-34.5831', '-58.4108', 4);


--
-- TOC entry 4859 (class 0 OID 16413)
-- Dependencies: 218
-- Data for Name: event_registrations; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 4861 (class 0 OID 16418)
-- Dependencies: 220
-- Data for Name: event_tags; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.event_tags VALUES (1, 1, 1);


--
-- TOC entry 4862 (class 0 OID 16421)
-- Dependencies: 221
-- Data for Name: events; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.events VALUES (1, 'Concierto de Jazz', 'Una noche de jazz en vivo', 1, 1, '20:00:00-03', 120, 1500, 1, 200, 1);


--
-- TOC entry 4863 (class 0 OID 16426)
-- Dependencies: 222
-- Data for Name: locations; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.locations VALUES (1, 'La Rural', '-34.5831', '-58.4108', 1);


--
-- TOC entry 4864 (class 0 OID 16431)
-- Dependencies: 223
-- Data for Name: provinces; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.provinces VALUES (1, 'BA', 'Buenos Aires', '-34.6037', '-58.3816', '1');


--
-- TOC entry 4865 (class 0 OID 16436)
-- Dependencies: 224
-- Data for Name: tags; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.tags VALUES (1, 'Jazz');


--
-- TOC entry 4866 (class 0 OID 16441)
-- Dependencies: 225
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.users VALUES (1, 'Lucía', 'Méndez', 'lucia.m', 'password123');
INSERT INTO public.users VALUES (2, 'Lucho', 'Martinez', 'lucho.m', '$2b$10$H6Xkel4VhIMtQ1OQWT/yQ.GYF9r7c71LCv9cz87M0lPlbb.JlpSeC');
INSERT INTO public.users VALUES (3, 'Valen', 'Ekes', 'ValenEkes', '$2b$10$shtB0led.32rxG1ZSOXFeOQuKzjK9Vpz5DneGuMumen68oDUoSI7C');
INSERT INTO public.users VALUES (4, 'Tomas', 'Sasson', 'T.Sasson', '$2b$10$mSepEavtQFF.eYBBzGgUX.4M22iZrMnRykofrKXR4vO6Qv8pSH7I.');


--
-- TOC entry 4876 (class 0 OID 0)
-- Dependencies: 227
-- Name: event_locations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.event_locations_id_seq', 11, true);


--
-- TOC entry 4877 (class 0 OID 0)
-- Dependencies: 219
-- Name: event_registrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.event_registrations_id_seq', 1, false);


--
-- TOC entry 4878 (class 0 OID 0)
-- Dependencies: 226
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 4, true);


--
-- TOC entry 4675 (class 2606 OID 16449)
-- Name: event_categories event_categories_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.event_categories
    ADD CONSTRAINT event_categories_pkey PRIMARY KEY (id);


--
-- TOC entry 4677 (class 2606 OID 16451)
-- Name: event_enrollments event_enrollments_id_id_event_id_user_id1_id_event1_id_user_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.event_enrollments
    ADD CONSTRAINT event_enrollments_id_id_event_id_user_id1_id_event1_id_user_key UNIQUE (id, id_event, id_user) INCLUDE (id, id_event, id_user);


--
-- TOC entry 4679 (class 2606 OID 16453)
-- Name: event_enrollments event_enrollments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.event_enrollments
    ADD CONSTRAINT event_enrollments_pkey PRIMARY KEY (id);


--
-- TOC entry 4681 (class 2606 OID 16455)
-- Name: event_locations event_locations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.event_locations
    ADD CONSTRAINT event_locations_pkey PRIMARY KEY (id);


--
-- TOC entry 4683 (class 2606 OID 16457)
-- Name: event_registrations event_registrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.event_registrations
    ADD CONSTRAINT event_registrations_pkey PRIMARY KEY (id);


--
-- TOC entry 4685 (class 2606 OID 16459)
-- Name: event_tags event_tags_id_tag_id_id_tag1_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.event_tags
    ADD CONSTRAINT event_tags_id_tag_id_id_tag1_key UNIQUE (id_tag) INCLUDE (id, id_tag);


--
-- TOC entry 4687 (class 2606 OID 16461)
-- Name: event_tags event_tags_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.event_tags
    ADD CONSTRAINT event_tags_pkey PRIMARY KEY (id_event);


--
-- TOC entry 4689 (class 2606 OID 16463)
-- Name: events events_id_evento_categoria_id_creator_user_id_evento_locaci_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT events_id_evento_categoria_id_creator_user_id_evento_locaci_key UNIQUE (id_evento_categoria, id_creator_user, id_evento_locacion) INCLUDE (id, id_evento_categoria, id_evento_locacion, id_creator_user);


--
-- TOC entry 4691 (class 2606 OID 16465)
-- Name: events events_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT events_pkey PRIMARY KEY (id);


--
-- TOC entry 4693 (class 2606 OID 16467)
-- Name: locations locations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.locations
    ADD CONSTRAINT locations_pkey PRIMARY KEY (id);


--
-- TOC entry 4695 (class 2606 OID 16469)
-- Name: provinces provinces_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.provinces
    ADD CONSTRAINT provinces_pkey PRIMARY KEY (id);


--
-- TOC entry 4697 (class 2606 OID 16471)
-- Name: tags tags_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tags
    ADD CONSTRAINT tags_pkey PRIMARY KEY (id);


--
-- TOC entry 4699 (class 2606 OID 16473)
-- Name: users users_id_id1_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_id_id1_key UNIQUE (id) INCLUDE (id);


--
-- TOC entry 4701 (class 2606 OID 16475)
-- Name: users usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT usuario_pkey PRIMARY KEY (id);


--
-- TOC entry 4702 (class 2606 OID 16476)
-- Name: event_enrollments event_enrollments_id_event_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.event_enrollments
    ADD CONSTRAINT event_enrollments_id_event_fkey FOREIGN KEY (id_event) REFERENCES public.events(id) NOT VALID;


--
-- TOC entry 4703 (class 2606 OID 16481)
-- Name: event_enrollments event_enrollments_id_user_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.event_enrollments
    ADD CONSTRAINT event_enrollments_id_user_fkey FOREIGN KEY (id_user) REFERENCES public.users(id) NOT VALID;


--
-- TOC entry 4704 (class 2606 OID 16486)
-- Name: event_locations event_locations_id_locations_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.event_locations
    ADD CONSTRAINT event_locations_id_locations_fkey FOREIGN KEY (id_locations) REFERENCES public.locations(id) NOT VALID;


--
-- TOC entry 4707 (class 2606 OID 16491)
-- Name: event_tags event_tags_id_event_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.event_tags
    ADD CONSTRAINT event_tags_id_event_fkey FOREIGN KEY (id_event) REFERENCES public.events(id) NOT VALID;


--
-- TOC entry 4708 (class 2606 OID 16496)
-- Name: events events_id_creator_user_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT events_id_creator_user_fkey FOREIGN KEY (id_creator_user) REFERENCES public.users(id) NOT VALID;


--
-- TOC entry 4709 (class 2606 OID 16501)
-- Name: events events_id_creator_user_fkey1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT events_id_creator_user_fkey1 FOREIGN KEY (id_creator_user) REFERENCES public.event_categories(id) NOT VALID;


--
-- TOC entry 4710 (class 2606 OID 16506)
-- Name: events events_id_evento_locacion_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT events_id_evento_locacion_fkey FOREIGN KEY (id_evento_locacion) REFERENCES public.event_locations(id) NOT VALID;


--
-- TOC entry 4705 (class 2606 OID 16511)
-- Name: event_registrations fk_event; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.event_registrations
    ADD CONSTRAINT fk_event FOREIGN KEY (id_event) REFERENCES public.events(id) ON DELETE CASCADE;


--
-- TOC entry 4706 (class 2606 OID 16516)
-- Name: event_registrations fk_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.event_registrations
    ADD CONSTRAINT fk_user FOREIGN KEY (id_user) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- TOC entry 4711 (class 2606 OID 16521)
-- Name: locations locations_id_provincia_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.locations
    ADD CONSTRAINT locations_id_provincia_fkey FOREIGN KEY (id_provincia) REFERENCES public.provinces(id) NOT VALID;


--
-- TOC entry 4712 (class 2606 OID 16526)
-- Name: tags tags_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tags
    ADD CONSTRAINT tags_id_fkey FOREIGN KEY (id) REFERENCES public.event_tags(id_tag) NOT VALID;


-- Completed on 2025-09-05 18:08:20

--
-- PostgreSQL database dump complete
--

